### PR TITLE
Adding support for private DTL VMs

### PR DESCRIPTION
**Pull request by flixman**
In Azure DTL builder, currently only VMs with public IP were taken into account. This PR adds support for private IP VMs also (through the addition of a config parameter), by setting the SSHHost to be the IP address in case a private IP is request or the tmpFQDN otherwise. Also, this PR introduces a specific timeout for the image capture step.

### CODE REVIEW

**Comment by flixman** [comment]
Hi @SwampDragons! I see there is an error related to a shell not being available in the agent running the lint on this PR. Is this something I can fix, somehow, or needs to be fixed by Hashicorp people?

**Review by nywilken — APPROVED** [review]
@flixman this looks good, thank you for the update. Your change for adding the winrm artifact fixes the failing windows acceptance test - 🙇 

I'm going to pull this in and add a fast follow PR to enable the acceptance tests and add documentation for the DTL builder and provisioner before cutting a release. 


```
~>  PACKER_ACC=1 AZURE_CLI_AUTH=1 go test -count 1 -v ./builder/azure/dtl/... -run='TestBuilderAcc_ManagedDisk_Windows' --timeout=120m
=== RUN   TestBuilderAcc_ManagedDisk_Windows
--- PASS: TestBuilderAcc_ManagedDisk_Windows (680.64s)
PASS
ok      github.com/hashicorp/packer-plugin-azure/builder/azure/dtl      681.036s

~>  PACKER_ACC=1 AZURE_CLI_AUTH=1 go test -count 1 -v ./builder/azure/dtl/... -run='TestBuilderAcc_ManagedDisk_Linux_Artifacts' --timeout=120m
=== RUN   TestBuilderAcc_ManagedDisk_Linux_Artifacts
--- PASS: TestBuilderAcc_ManagedDisk_Linux_Artifacts (767.67s)
PASS
ok      github.com/hashicorp/packer-plugin-azure/builder/azure/dtl      768.046s
```

**Comment by flixman** [comment]
Hi @nywilken! Thank you. I have seen that the check fmt and check lint were still throwing messages, and failing (sorry for that). Is enough to add commits to re-trigger those checks? or every time somebody will have to approve the PR?

**Comment by nywilken** [comment]
Hi @flixman thanks for the quick turn around on the test fix and the gofmt issue. I wouldn't worry about the latest check failure those are within the older code base that needs to be refactored a bit. Thanks for pushing this forward again. 

I just crated https://github.com/hashicorp/packer-plugin-azure/pull/86 which adds the documentation I mentioned. I will merge in your changes now and rebase so that it is just incremental to the work you've done.

**Pull request merged**
