### PR TITLE
Add support for using a custom SSHHost address

### PR DESCRIPTION
**Pull request by csetariq**
* Override with `ssh_host` config option if supplied

Same as hashicorp/packer#7832

### CODE REVIEW

**Comment by csetariq** [comment]
@nywilken I couldn't figure out why MDX doc generation differs for this change. Could you help me figure this out?

**Comment by nywilken** [comment]
> @nywilken I couldn't figure out why MDX doc generation differs for this change. Could you help me figure this out?

Hi @csetariq thanks for bubbling this up. This is an issue with our tooling that has been fixed but not yet released https://github.com/hashicorp/packer-plugin-sdk/pull/212. 

You can ignore it for now and we can fix in on merge. Feel free to drop the WIP when you're ready to have the PR reviewed.

**Review by nywilken — COMMENTED** [review]
For the record the change looks good. I don't see that we have any test for validating that we get a value for sshHost. You can add a test to builder_test.go that sets an ssh_host value and validates the behavior. 

```go
func TestBuilderConfig_SSHHost(t *testing.T) {
	var testSubject Builder
	builderValues := getArmBuilderConfiguration()
	builderValues["communicator"] = "ssh"
	builderValues["ssh_username"] = "override_username"
	builderValues["ssh_host"] = "172.10.10.3"
	_, _, err := testSubject.Prepare(builderValues)
	if err != nil {
		t.Fatalf("failed to prepare: %s", err)
	}

	//inject Fake IP into state for SSHHost
	testSubject.stateBag.Put(constants.SSHHost, "127.0.0.1")

	if _, ok := testSubject.stateBag.GetOk(constants.SSHHost); ok == false {
		t.Fatal("Expected the state bag to contain '127.0.0.1' for SSHHost but it did not.")
	}

	sshHostFn := communicator.CommHost(testSubject.config.Comm.SSHHost, constants.SSHHost)
	host, err := sshHostFn(testSubject.stateBag)
	if err != nil {
		t.Errorf("Unexpected error occurred obtaining ssh_host: %s", err)
	}
	if host != "172.10.10.3" {
		t.Errorf("Expected custom ssh_host to take precedences over state value but it got %q", host)
	}
}
```

**Comment by csetariq** [comment]
Sure, this is helpful. Let me come back with a test.

**Comment by nywilken** [comment]
I rebased and added the missing test. Once it goes green I will merge.

**Review by nywilken — APPROVED** [review]
All good there. Thanks again for the change.

**Pull request merged**
