### PR TITLE
Change adminPassword type from string to securestring in VM deployment

### PR DESCRIPTION
**Pull request by feiyushi**
This PR changes the `adminPassword` type from `string` to `securestring` in VM deployment for enhanced security.

### CODE REVIEW

**Comment by feiyushi** [comment]
Hi @nywilken, Could packer maintainers cut a release for this plugin after the PR is accepted and merged? Thanks! (I got your name from past PRs, sorry for the spam)

**Review by sumit-kalra — APPROVED** [review]

**Comment by sumit-kalra** [comment]
This change LGTM. Please consider waiting for maintainers to sign-off as well.

**Review by azr — APPROVED** [review]
LGTM !

**Pull request merged**
